#!/usr/bin/env node
import { تشغيل_الف } from "./src/Models/AlifRun.js";
import { بناء_الف } from "./src/Models/AlifBuild.js";

import { pubLib } from "./AlifLib.js";
import { getLib } from "./AlifLib.js";
import { updateLib } from "./AlifLib.js";
import { alifUpdate } from "./AlifLib.js";

// المدخلات في الطرفية
const command = process.argv[2];
export const fileName = process.argv[3];

if (["-v", "ص", "اصدار"].includes(command)) {
    console.log(`0.1.0 اصدار لغة الف للويب`);
} else if (["-h", "م", "مساعدة"].includes(command)) {
    console.log(`
    -v, ص, اصدار: اصدار اللغة.
    -h, م, مساعدة: اظهار هاذه القائمة
    اسم_الملف.الف: تشغيل ملف محدد.
    عدم كتابة شئ: تشغيل ملف رئيسي.الف.
    `);
} else if (["build", "بناء"].includes(command)) {
    if (fileName && (fileName.endsWith(".alif") || fileName.endsWith(".الف"))) {
        بناء_الف(fileName);
    } else {
        بناء_الف();
    }
} else if (["pub", "publish", "نشر"].includes(command)) {
    pubLib();
} else if (["get", "install", "i", "تحميل"].includes(command)) {
    getLib();
} else if (["update", "تحديث"].includes(command)) {
    if (fileName) {
        updateLib();
    } else {
        alifUpdate(false);
        alifUpdate(true);
    }
} else {
    if (command && (command.endsWith(".alif") || command.endsWith(".الف"))) {
        تشغيل_الف(command);
    } else {
        تشغيل_الف();
    }
}
