#!/usr/bin/env node
import { تشغيل_الف } from "./src/Models/AlifRun.js";
import { بناء_الف } from "./src/Models/AlifBuild.js";
import fs from "fs";
import path from "path";

// المدخلات في الطرفية
const command = process.argv[2];
const fileName = process.argv[3];

if (["-v", "ص", "اصدار"].includes(command)) {
    const __filename = new URL(import.meta.url).pathname;
    const __dirname = path.dirname(__filename);
    const packageJson = JSON.parse(
        fs.readFileSync(path.join(__dirname, "package.json"), "utf8")
    );
    console.log(`${packageJson.version} اصدار لغة الف للويب`);
} else if (["-h", "م", "مساعدة"].includes(command)) {
    console.log(`
    -v, ص, اصدار: اصدار اللغة.
    -h, م, مساعدة: اظهار هاذه القائمة
    اسم_الملف.الف: تشغيل ملف محدد.
    عدم كتابة شئ: تشغيل ملف رئيسي.الف.
    `);
} else if (["build", "بناء"].includes(command)) {
    if (fileName && (fileName.endsWith(".alif") || fileName.endsWith(".الف"))) {
        بناء_الف(fileName);
    } else {
        بناء_الف();
    }
} else {
    if (command && (command.endsWith(".alif") || command.endsWith(".الف"))) {
        تشغيل_الف(command);
    } else {
        تشغيل_الف();
    }
}
